### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by p1206-htwg** [markusheilig/business-plan#10]
Am besten fasst jeder zu seinen Kapiteln das absolut Wichtigste zusammen. Die Sätze sollten am Schluss dann zusammengefasst werden zu der executive summary.
Die Executive Summary muss meines Wissens nach nicht in Abschnitte nach Kapiteln unterteilt werden, sondern sollte ein kurzer, fliessender Text sein.

(Meine Sätze habe ich ganz unten hinzugefügt):

https://github.com/markusheilig/business-plan/edit/master/executive_summary.tex

**Comment by markusheilig** [comment]
AN ALLE: ich habe den executive summary GROB geschrieben, bitte schreibt noch jeder von euch 1 oder 2 sätze dazu, dann ist das ding mal gegessen.

@p1206-htwg: was meinst du mit "Die Funktionsweise der App ermöglicht es unserem Unternehmen, wertvollen Content in hohem Volumen quasi kostenfrei zu erhalten."? verstehe ich nicht.
Zudem weiß ich nicht genau, wie ich deine weiteren texte sinnvoll in den executive summary einbauen kann. bitte selbst machen (sollte ja schnell passiert sein)

**Comment by sebirkli** [comment]
Habt ihr für eure Thesis auch jedes Kapitel in die executive summary rein?

**Comment by markusheilig** [comment]
ja, jeweils ca. 1 satz. mit deinen kapiteln zeigst du ja, was du gemacht hast in deiner Thesis. und im abstract willst du ja auch kurz vorstellen, was sinn dieser arbeit ist

**Comment by p1206-htwg** [comment]
@markusheilig: damit war gemeint, dass die user selbst den content generieren (mind. bei jedem login-täglich)
Die executive summary sieht nun gut aus, habe die doppelten notizen rausgemacht. Issue könnte also geschlossen werden.
