### ISSUE TITLE
wichtige infos zu jedem kapitel

### ISSUE THREAD

**Issue by markusheilig** [markusheilig/business-plan#2]
Unsere Dozentin hält sich wohl stark an das "Gründerhandbuch".
Hier wird zu jedem Kapitel noch einmal das Wichtigste zusammengefasst:

http://www.senkrechtstarter.de/fileadmin/downloads/Gruenderhandbuch_komplett_web.pdf

**Comment by rugo** [comment]
FYI: Laut Folien soll unserer Businessplan 7-9 Seiten lang sein! Also nicht an den Seitenzahlen im Dokument orientieren.

**Comment by markusheilig** [comment]
jup, ist klar. ich wollte mit dem PDF nur zeigen, welche info's im jeweiligen Kapitel wichtig sind. die Folien zur Vorlesung geben nämlich (meiner Meinung nach) nicht genügend her!

**Comment by sebirkli** [comment]
Who the fuck is rugo?

**Comment by rugo** [comment]
Ja, dachte nur ich geb den Hinweis, weil wir uns fast auf 35 Seiten geeinigt hätten :o

**Comment by sebirkli** [comment]
Muss dieses Riesendiagramm (Realisierungsfahrplan) eigentlich nicht in den Anhang?

**Comment by p1206-htwg** [comment]
Hey Sergey, waren die Stichpunkte laut Issue4 ok? oder hat sich da etwas geändert?

**Comment by sebirkli** [comment]
Ne ich hab nichts weiter geändert. Mache mich jetzt an die SWOT-Analyse für Chancen und Risiken ran.

**Comment by p1206-htwg** [comment]
Nur um sicherzugehen: die meine Stichpunkte auf https://github.com/markusheilig/business-plan/blob/master/geschaeftsmodell_und_organisation.tex setzen voraus, dass der Teil von Nico und der Marketing Teil von dir dazu passen. Wenn ich richtig verstehe, passt das alles und ich kann mit dem Schreiben anfangen. Bitte um kurze Bestätigung, sorry der Nachfrage :-)

**Comment by sebirkli** [comment]
Ich check nicht was du genau meinst...
Ich habe Markt und Wettbewerb gemacht und bin jetzt an Chancen u. Risiken dran. Nico ist für  Produkt/Dienstleistung u. MARKETING!!! verantwortlich.
Was meinst du mit "..und der Marketing Teil von dir..."

**Comment by p1206-htwg** [comment]
verstehe, ich habe die Aufteilung verwechselt

**Comment by sebirkli** [comment]
@Niwonneb kannst du bitte deine 5000k Deutschfehler entfernen? :)

**Comment by p1206-htwg** [comment]
@sebirkli falls du für mich über @Niwonneb Marketing-Teil schaust, musst du das nicht machen, aber danke

**Comment by markusheilig** [comment]
Diagramm muss rein, das ist der Hauptteil des Realisierungsfahrplans
