### ISSUE TITLE
Business Model Canvas

### ISSUE THREAD

**Issue by markusheilig** [markusheilig/business-plan#3]
Ein Bonuspunkt könnten wir sicherlich durch eine ausgefüllte Business-Model-Canvas bekommen.
Diese (so mein Vorschlag) kann ganz einfach am Ende erstellt werden und dann als Anhang in den BP rein.

Erklärung und Beispiel: http://de.slideshare.net/andreasdiehl2/business-model-canvas-workshop-40405037

Template gibts hier: https://upload.wikimedia.org/wikipedia/commons/1/10/Business_Model_Canvas.png

Die einzelnen Punkte der BMC (Key Partners, Key Activities, Value Propositions, ...) kann man ja einfach als Kommentar unter dieses Issue schreiben.

**Comment by p1206-htwg** [comment]
voraussichtlich overkill. Noch Restaufgaben zu bewältigen. Wird daher geschlossen.
