### ISSUE TITLE
Bitte Stichpunkte überprüfen @sergej @ nico

### ISSUE THREAD

**Issue by p1206-htwg** [markusheilig/business-plan#4]
Da noch nicht viele Unterlagen hochgeladen wurden, habe ich schon mit dem Geschäftsplan/Organisation begonnen:
https://github.com/markusheilig/business-plan/blob/master/geschaeftsmodell_und_organisation.tex

Ich werde den Teil "Geschäftsplan und Organisation" entsprechend in Kürze ausformulieren. Den Finanzteil werde ich vermutlich kurz (aber möglichst genau) halten.
Falls es etwas zu beanstanden gibt, einfach melden (bitte möglichst bald).  Ansonsten: **Achtet darauf, dass eure Teile möglichst zu diesen Stichpunkten passen**

@Markus: hab dich noch ergänzt wegen dem Personalteil: (einfach nach "Markus" suchen (mehrmals) und "Unternehmerteam, Management und Personal"). Dein Abschnitt über Nico/Designer kann ich leicht abändern und hier reinkopieren. Bzw. kannst du den Teil später alternativ bei dir reinkopieren 
@Nico: wegen Kosten, suche "Kosten für den Kunden und Preispolitik". Die Marketingkosten sind nicht drin, nur die Kostenstruktur für die Kunden. Gib die Marketingpreise einfach durch, dann kann ich schauen, wann sich das Vorhaben bei der Konstellation lohnt. Kommt dann in das Kapitel "Finanzplanung und Finanzierung" rein.

**Comment by p1206-htwg** [comment]
kapitel sind fertig.

**Comment by nico** [comment]
Falscher Nico.
