### ISSUE TITLE
wann seid ihr alle ungefährt fertig?

### ISSUE THREAD

**Issue by p1206-htwg** [markusheilig/business-plan#5]
da ich den Eindruck habe, dass eure Teile doch nicht ganz angepasst waren an die hochgeladenen Stichpunkte zur Geschäftsorganisation, fange ich besser an, wenn ihr alle fertig seid.

Nico hat heute morgen noch eine fast finale Version hochgeladen. Wie sieht es mit Sergej und Markus aus?

**Comment by sebirkli** [comment]
Ich wollte es morgen fertig machen. Aber da du erst anfangen möchtest wenn wir fertig sind, schau ich heut abend mal rein.

Am 09.07.2016 09:25 schrieb "p1206-htwg" notifications@github.com:

**Comment by markusheilig** [comment]
mein teil ist fast fertig, muss nur in dem gantt-diagramm noch ne kleinigkeit anpassen

**Comment by p1206-htwg** [comment]
@sebirkli , kannst du sicherheitshalber  ein paar Kern-Stichpunkte zu deinem Teil hochladen? Am besten noch vor 18 Uhr? Dann kann ich mit dem Schreiben heute anfangen und vlt heute noch fertig werden. Wenn ich Glück hab, kann ich das meiste beim alten lassen. Die Stichpunkte sind nach wie vor auf https://github.com/markusheilig/business-plan/blob/master/geschaeftsmodell_und_organisation.tex
(siehe Issue 4)

Sonst sag einfach, ob ich weiterhin mit den Stichpunkten arbeiten kann, das würde mir schon reichen.

**Comment by Niwonneb** [comment]
Ich bin jetzt im Groben fertig. Natürlich kann man alles noch Abändern oder was hinzufügen.

**Comment by p1206-htwg** [comment]
kapitel sind fertig
