### ISSUE TITLE
Marketing: bitte ergänzen/ @Nico

### ISSUE THREAD

**Issue by p1206-htwg** [markusheilig/business-plan#9]
@Niwonneb 
bitte den folgenden Teil noch in den Abschnitt "Marketing" reinnehmen: (hiervon wurde einiges noch nicht erwähnt im Marketing)
###### 

 •Kundensegmente: Beschreiben Sie, wen genau Sie als Kunden erreichen und bedienen wollen.
 -kundensegment: erstlinig die junge generation: ab 16 bis 35, aber natürlich auszuweiten für alle alterklassen, wobei
 die älteren natürlich nicht so häufig auf smartphones/social networks herumtreiben. 

 aus diesem grund wird auch gezielte werbung für diese Zielgruppe gemacht, siehe marketing.
 Die Kunden erstrecken sich über den Globus, allerdings macht es sinn sich auf die Kundschaft entsprechend unserer Marketingstrategie zu konzentrieren,
 sprich:geographischer Aspekt der Kunden: Deutschland, UK, Frankreich, Spanien, wenig gelder in andere europische länder,
 hauptgelder schon eher dann in usa, da in europa über die grossen länder bereits mund zu mund propaganda betrieben wird 
 und man hier an werbegeldern etwas sparen kann für die restlichen verbleibenden länder

 -Vertriebs/Kommunikationskanäle:
 Über facebook zielgruppe wählen, dann bezahlen, rest übernimmt facebook.
 Kriterien für facebook-wahle zum einstellen:
 Alter: 16-34
 -hobbys/interessen: reisen, life, happiness, travel, adventure, landesspezifische hashtags love,paris,berlin,etc.
 -hauptsächlich europa, Nordamerika asien  zuerst in dieser reihenfolge.
 damit sollte schon genug marketing geld fürs erste ausgebucht sein.
 je etablierter die app wird (schneeballeffekt), umso besser läuft die mund zu mund propaganda
 umso mehr wird der vertrieb von selbst statt finden. dennoch: wenn der cashflow stärker wird (gewinne nicht unbedingt)
 kann man das geld gleich für weitere werbungen einsetzen, vor allem verstärkt in asien und in den anderen noch nicht erfassten 
 kontinenten/ländern, bevor hier nachahmer aktiv werden. Geschwindigkeit zählt am anfang mehr, dadurch sind langfristige rentabilitäten eher garantiert (schutz vor nachahmer)

update: wie du im Geschäftsplan siehst (https://github.com/markusheilig/business-plan/blob/master/geschaeftsmodell_und_organisation.tex) ist für das Marketing ein Fokus von Deutschland, auf Europa, auf den USA dann auf Asien in dieser Reihenfolge grob geschildert. Oben ist das natürlich viel genauer aufgeführt.

**Comment by markusheilig** [comment]
ich nehm mich mal raus, marketing ist nicht mein teil.

**Comment by Niwonneb** [comment]
Euch ist bewusst, dass wir schon 20 Seiten haben?
Wir müssten eigentlich Sachen raus machen, nicht dazu.

**Comment by p1206-htwg** [comment]
Beim Durchgehen des Marketings habe ich den Eindruck gehabt, dass zu viel Allgemeines angegeben wurde, nicht aber eine konkrete Strategie. Wo werben wir (Land)? Wie sehen die ersten Leute genau aus, die wir erreichen wollen etc.? Dass man einen guten Kundendienst anbieten möchte, ist nicht schlecht, aber das sagen eigentlich alle :)
Genau genommen finde ich, wäre diese Info viel wichtiger. Klar könnt ihr entscheiden, was am besten passt, mit 20 Seiten stehen wir eigtl schon gut da.

**Comment by p1206-htwg** [comment]
stehen kurz vor der Abgabe, wird in issue 7 diskutiert-> wird geschlossen
